import { SOURCES, type Source } from '../constants';
import { config } from '../config';

/**
 * Source variant links (M1) and source resolution (PRD rule R6).
 *
 * One public URL per source in §6.7, all resolving to the same apply page and
 * differing only in the source they stamp on the resulting application. The
 * list is generated by iterating the SOURCES enum, so it cannot drift from
 * the PRD as sources are added.
 *
 * Canonical shape:  {base}/apply/{public_slug}/{source}
 * Bare campaign link: {base}/apply/{public_slug}   -> resolves to `other`
 *
 * R6: the apply page must render, and the application must be accepted, for
 * any valid slug regardless of what follows it. Links get forwarded,
 * truncated and mangled constantly; a mis-tagged source is a reporting
 * nicety, a lost candidate is not recoverable. resolveSource therefore never
 * throws and never rejects — anything it cannot recognise becomes `other`.
 */

export interface SourceVariantLink {
  source: Source;
  url: string;
}

/** The public base URL for candidate-facing links (§13.6 careers subdomain). */
export function publicBaseUrl(): string {
  return (config.careersBaseUrl ?? config.appBaseUrl).replace(/\/+$/, '');
}

/** The bare campaign link, with no source segment. Resolves to `other`. */
export function applyPath(slug: string): string {
  return `/apply/${encodeURIComponent(slug)}`;
}

export function applyUrl(slug: string): string {
  return `${publicBaseUrl()}${applyPath(slug)}`;
}

/** One distinct URL per source in §6.7. */
export function sourceVariantLinks(slug: string): SourceVariantLink[] {
  const base = publicBaseUrl();
  return SOURCES.map((source) => ({
    source,
    url: `${base}${applyPath(slug)}/${source}`,
  }));
}

/**
 * Maps the source segment of an apply URL to a source enum value.
 *
 * Never throws, never rejects (R6). Absent, unrecognised, corrupted or
 * mangled input resolves to `other` so the page still renders and the
 * application is still accepted. Tolerates the common ways a forwarded link
 * degrades: case changes, surrounding whitespace or punctuation, hyphens in
 * place of underscores, and trailing query or fragment debris.
 */
export function resolveSource(raw: string | string[] | null | undefined): Source {
  const candidate = Array.isArray(raw) ? raw[0] : raw;
  if (typeof candidate !== 'string') return 'other';

  const normalised = candidate
    .trim()
    .toLowerCase()
    .split(/[?#]/)[0] // drop ?utm=... / #anchor debris
    .replace(/[-\s]+/g, '_') // "website-direct" -> "website_direct"
    .replace(/\/+$/, ''); // trailing slash from a copied folder-style URL

  return (SOURCES as readonly string[]).includes(normalised) ? (normalised as Source) : 'other';
}
